export const SET_DATA = "SET_DATA";
export const FILTER_ALL = "FILTER_ALL";
export const FILTER_WITHOUT_TRANSFER = "FILTER_WITHOUT_TRANSFER";
export const FILTER_ONE_TRANSFER = "FILTER_ONE_TRANSFER";
export const FILTER_TWO_TRANSFER = "FILTER_TWO_TRANSFER";
export const FILTER_THREE_TRANSFER = "FILTER_THREE_TRANSFER";
